### ISSUE TITLE
is this still maintain or a dead end

### ISSUE THREAD

**Issue by satfreak** [boretom/optware#4]
Is some still maintaining this project, or is gone a quit dead.
Because if i look in de repository, only old packets can be found.
Which is a shame, as the demand on a good optware with 64 bits is badly needed.

**Comment by boretom** [comment]
Hey @satfreak, it got created because I needed Optware 64-bit for ASUSTOR. Haven't got much time these days since work had catched up with me.

[Optware-ng](https://github.com/Optware/Optware-ng) got launched and the packages are updated. Unfortunately no 64-bit yet.

But then there's [Entware-ng](https://github.com/Entware-ng/Entware-ng) which got started because of outdated Optware. And they got 64-bit packages.
